In [2]:
print("Hello World")

Hello World


In [ ]:
a,b=map(int, input().split())

In [ ]:
# TO add markdown
# Enter "esc+1"

# Markdown

In [5]:
import numpy as np
print(np.__version__)

1.23.5


In [11]:
a=np.array([[1],[2]])

In [17]:
a[1]

array([2])

In [18]:
for i in a:
    print(i)

[1]
[2]


# Different ways of creating array

In [19]:
a1=np.arange(5)
a1

array([0, 1, 2, 3, 4])

In [22]:
a2=np.zeros((2,4), dtype="int")
a2

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
a3=np.full((4,6), dtype="float", fill_value="7" )
a3

array([[7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.]])

In [28]:
a4=np.ones(2)
a4

array([1., 1.])

# Slicing

In [42]:
a3[0:7] 
a3

array([[7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.]])

# Pandas
